### ISSUE TITLE
"lateinit property default has not been initialized"

### ISSUE THREAD

**Issue by copygirl** [DaemonicLabs/Voodoo#17]
Voodoo build: 118
Workspace setup:
```
java -jar bootstrap-voodoo.jar
./gradlew createPack --id hardcorebytes --mcVersion 1.12.2 --title "Hardcore Bytes"
```
----
Pack file: [hardcorebytes.voodoo.jar](https://gist.github.com/copygirl/4647c30ed4853f6fc0512531ab882aaf#file-hardcorebytes-voodoo-kts)
Command run:
```
java -jar bootstrap-voodoo.jar packs/hardcorebytes.voodoo.kts build - test mmc
```
----

Full output: [voodoo.log](https://gist.github.com/copygirl/4647c30ed4853f6fc0512531ab882aaf#file-voodoo-log)

```
11:00:54.956 [main] .(Directories.kt:91)                INFO  - Using XDG directories
11:00:54.975 [main] .(Voodoo.kt:74)                     DEBUG - id: hardcorebytes
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property default has not been initialized
        at voodoo.util.SharedFolders$RootDir.getDefault(SharedFolders.kt:13)
        at voodoo.util.SharedFolders$RootDir$resolver$1.invoke(SharedFolders.kt:14)
        at voodoo.util.SharedFolders$RootDir$resolver$1.invoke(SharedFolders.kt:11)
        at voodoo.util.SharedFolders$RootDir.get(SharedFolders.kt:15)
        at voodoo.Voodoo.main(Voodoo.kt:76)
```

**Comment by NikkyAI** [comment]
fixed in 4412ee6a02fbf4440a83f55510088d53f842392e
